server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: payment_routh
#          uri: http://localhost:8001
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/get/**

        - id: payment_routh2
#          uri: http://localhost:8001
          uri: lb://cloud-payment-service
#          filters:
#            - AddRequestParameter=X-Request-Id,1024
          predicates:
            - Path=/payment/lb/**
            - After=2021-01-08T14:17:06.163+08:00[Asia/Shanghai]
#            - Cookie=username,oyy
#            - Header=X-Request-Id, \d+
#            - HOST=**.atguigu,com
#            - Method=GET
#            - Query=username,\d+
eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
